name: Test

on:
    pull_request:
        branches:
            - "*"

jobs:
    run-tests:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: "15"
                  check-latest: true
            - run: npm ci

            - name: Run tests
              run: npm run test

            - name: NYC Coverage Report
            - uses: Tintef/nyc-reporter-action@0.1.0
              with:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  REPORTER: "text" # defaults to 'text-summary'
